;Tarea creada
SERVER OFF
SERVIDOR DETENIDO
& C:/USERS/BRAUL/APPDATA/LOCAL/MICROSOFT/WINDOWSAPPS/PYTHON3.12.EXE C:/USERS/BRAUL/DOCUMENTS/GITHUB/INTEGPOO/SERVIDOR/SRC/CLI.PY
& C:/USERS/BRAUL/APPDATA/LOCAL/MICROSOFT/WINDOWSAPPS/PYTHON3.12.EXE C:/USERS/BRAUL/DOCUMENTS/GITHUB/INTEGPOO/SERVIDOR/SRC/CLI.PY
